"""Initial database schema with all models

Revision ID: 9a1ba78ab4db
Revises: 
Create Date: 2025-11-05 11:04:10.940586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a1ba78ab4db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_tools',
    sa.Column('base_tool_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('handler_class', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('base_tool_id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('llm_models',
    sa.Column('llm_model_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('cost_per_1k_input_tokens', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('cost_per_1k_output_tokens', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('llm_model_id')
    )
    op.create_index(op.f('ix_llm_models_is_active'), 'llm_models', ['is_active'], unique=False)
    op.create_index('ix_llm_models_provider_model', 'llm_models', ['provider', 'model_name'], unique=False)
    op.create_table('output_formats',
    sa.Column('format_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('renderer_hint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('format_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tenants',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_table('agent_configs',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('llm_model_id', sa.UUID(), nullable=False),
    sa.Column('default_output_format_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('handler_class', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['default_output_format_id'], ['output_formats.format_id'], ),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.llm_model_id'], ),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_agent_configs_is_active'), 'agent_configs', ['is_active'], unique=False)
    op.create_table('tenant_llm_configs',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('llm_model_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('rate_limit_tpm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.llm_model_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index(op.f('ix_tenant_llm_configs_llm_model_id'), 'tenant_llm_configs', ['llm_model_id'], unique=False)
    op.create_table('tenant_widget_configs',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('widget_key', sa.String(length=64), nullable=False),
    sa.Column('widget_secret', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('auto_open', sa.Boolean(), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('placeholder_text', sa.String(length=255), nullable=True),
    sa.Column('allowed_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_session_duration', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('enable_file_upload', sa.Boolean(), nullable=True),
    sa.Column('enable_voice_input', sa.Boolean(), nullable=True),
    sa.Column('enable_conversation_history', sa.Boolean(), nullable=True),
    sa.Column('embed_script_url', sa.String(length=500), nullable=True),
    sa.Column('embed_code_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_regenerated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index(op.f('ix_tenant_widget_configs_widget_key'), 'tenant_widget_configs', ['widget_key'], unique=True)
    op.create_table('tool_configs',
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_tool_id', sa.UUID(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_format_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['base_tool_id'], ['base_tools.base_tool_id'], ),
    sa.ForeignKeyConstraint(['output_format_id'], ['output_formats.format_id'], ),
    sa.PrimaryKeyConstraint('tool_id')
    )
    op.create_index(op.f('ix_tool_configs_base_tool_id'), 'tool_configs', ['base_tool_id'], unique=False)
    op.create_index(op.f('ix_tool_configs_is_active'), 'tool_configs', ['is_active'], unique=False)
    op.create_table('agent_tools',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_configs.agent_id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool_configs.tool_id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    op.create_index('ix_agent_tools_agent_priority', 'agent_tools', ['agent_id', 'priority'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('thread_id', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_message_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_configs.agent_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_last_message_at'), 'sessions', ['last_message_at'], unique=False)
    op.create_index('ix_sessions_tenant_user', 'sessions', ['tenant_id', 'user_id', 'created_at'], unique=False)
    op.create_table('tenant_agent_permissions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('output_override_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_configs.agent_id'], ),
    sa.ForeignKeyConstraint(['output_override_id'], ['output_formats.format_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'agent_id')
    )
    op.create_index(op.f('ix_tenant_agent_permissions_enabled'), 'tenant_agent_permissions', ['enabled'], unique=False)
    op.create_table('tenant_tool_permissions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool_configs.tool_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'tool_id')
    )
    op.create_index(op.f('ix_tenant_tool_permissions_enabled'), 'tenant_tool_permissions', ['enabled'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_messages_session_timestamp', 'messages', ['session_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_session_timestamp', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_tenant_tool_permissions_enabled'), table_name='tenant_tool_permissions')
    op.drop_table('tenant_tool_permissions')
    op.drop_index(op.f('ix_tenant_agent_permissions_enabled'), table_name='tenant_agent_permissions')
    op.drop_table('tenant_agent_permissions')
    op.drop_index('ix_sessions_tenant_user', table_name='sessions')
    op.drop_index(op.f('ix_sessions_last_message_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_agent_tools_agent_priority', table_name='agent_tools')
    op.drop_table('agent_tools')
    op.drop_index(op.f('ix_tool_configs_is_active'), table_name='tool_configs')
    op.drop_index(op.f('ix_tool_configs_base_tool_id'), table_name='tool_configs')
    op.drop_table('tool_configs')
    op.drop_index(op.f('ix_tenant_widget_configs_widget_key'), table_name='tenant_widget_configs')
    op.drop_table('tenant_widget_configs')
    op.drop_index(op.f('ix_tenant_llm_configs_llm_model_id'), table_name='tenant_llm_configs')
    op.drop_table('tenant_llm_configs')
    op.drop_index(op.f('ix_agent_configs_is_active'), table_name='agent_configs')
    op.drop_table('agent_configs')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('output_formats')
    op.drop_index('ix_llm_models_provider_model', table_name='llm_models')
    op.drop_index(op.f('ix_llm_models_is_active'), table_name='llm_models')
    op.drop_table('llm_models')
    op.drop_table('base_tools')
    # ### end Alembic commands ###
